AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Orders App - RDS PostgreSQL Multi-AZ (imports DB subnets + DB SG from networking stack).

Parameters:
  ExportPrefix:
    Type: String
    Default: orders-app

  DBName:
    Type: String
    Default: ordersdb
    MinLength: 1
    MaxLength: 63
    AllowedPattern: "^[a-zA-Z][a-zA-Z0-9_]*$"

  DBInstanceIdentifier:
    Type: String
    Default: orders-app-postgres
    MinLength: 1
    MaxLength: 63
    AllowedPattern: "^[a-zA-Z][a-zA-Z0-9-]*$"

  DBInstanceClass:
    Type: String
    Default: db.t4g.micro

  AllocatedStorageGB:
    Type: Number
    Default: 20
    MinValue: 20

  EngineVersion:
    Type: String
    Default: "16.3"

  MasterUsername:
    Type: String
    Default: postgres
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "^[a-zA-Z][a-zA-Z0-9_]*$"

  MasterUserPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 41

  BackupRetentionDays:
    Type: Number
    Default: 7
    MinValue: 0
    MaxValue: 35

  DeletionProtection:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]

Resources:
  OrdersAppDbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Orders App DB subnets (private) in AZ A/B
      SubnetIds:
        - !ImportValue
          Fn::Sub: "${ExportPrefix}:PrivateDbSubnetAzAId"
        - !ImportValue
          Fn::Sub: "${ExportPrefix}:PrivateDbSubnetAzBId"
      Tags:
        - Key: Name
          Value: orders-app-db-subnet-group

  OrdersAppPostgresDb:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      Engine: postgres
      EngineVersion: !Ref EngineVersion
      DBName: !Ref DBName
      MultiAZ: true
      DBSubnetGroupName: !Ref OrdersAppDbSubnetGroup
      VPCSecurityGroups:
        - !ImportValue
          Fn::Sub: "${ExportPrefix}:DbSecurityGroupId"
      PubliclyAccessible: false
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref AllocatedStorageGB
      StorageType: gp3
      StorageEncrypted: true
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      BackupRetentionPeriod: !Ref BackupRetentionDays
      CopyTagsToSnapshot: true
      DeletionProtection: !Equals [!Ref DeletionProtection, "true"]

Outputs:
  DbEndpointAddress:
    Value: !GetAtt OrdersAppPostgresDb.Endpoint.Address
    Export:
      Name: !Sub "${ExportPrefix}:DbEndpointAddress"

  DbEndpointPort:
    Value: !GetAtt OrdersAppPostgresDb.Endpoint.Port
    Export:
      Name: !Sub "${ExportPrefix}:DbEndpointPort"
