AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Orders App - RDS PostgreSQL Multi-AZ (private DB subnets AZ A/B) governed by orders-app-sg-db.

Parameters:
  PrivateDbSubnetAzAId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for orders-app-private-db-az-a

  PrivateDbSubnetAzBId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for orders-app-private-db-az-b

  DbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for orders-app-sg-db

  DBName:
    Type: String
    Default: ordersdb
    MinLength: 1
    MaxLength: 63
    AllowedPattern: "^[a-zA-Z][a-zA-Z0-9_]*$"
    Description: Initial database name

  DBInstanceIdentifier:
    Type: String
    Default: orders-app-postgres
    MinLength: 1
    MaxLength: 63
    AllowedPattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
    Description: RDS instance identifier

  DBInstanceClass:
    Type: String
    Default: db.t4g.micro
    Description: RDS instance class (pick what fits your workload)

  AllocatedStorageGB:
    Type: Number
    Default: 20
    MinValue: 20
    Description: Allocated storage in GB

  EngineVersion:
    Type: String
    Default: "16.3"
    Description: PostgreSQL engine version (adjust as needed)

  MasterUsername:
    Type: String
    Default: postgres
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "^[a-zA-Z][a-zA-Z0-9_]*$"
    Description: Master username

  MasterUserPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 41
    Description: Master password (NoEcho)

  BackupRetentionDays:
    Type: Number
    Default: 7
    MinValue: 0
    MaxValue: 35

  DeletionProtection:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]

Resources:
  OrdersAppDbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Orders App DB subnets (private) in AZ A/B
      SubnetIds:
        - !Ref PrivateDbSubnetAzAId
        - !Ref PrivateDbSubnetAzBId
      Tags:
        - Key: Name
          Value: orders-app-db-subnet-group

  OrdersAppPostgresDb:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      Engine: postgres
      EngineVersion: !Ref EngineVersion
      DBName: !Ref DBName

      # Multi-AZ (synchronous standby in the other AZ)
      MultiAZ: true

      # Networking / placement
      DBSubnetGroupName: !Ref OrdersAppDbSubnetGroup
      VPCSecurityGroups:
        - !Ref DbSecurityGroupId
      PubliclyAccessible: false

      # Sizing / storage
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref AllocatedStorageGB
      StorageType: gp3
      StorageEncrypted: true

      # Credentials
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword

      # Ops / durability
      BackupRetentionPeriod: !Ref BackupRetentionDays
      CopyTagsToSnapshot: true
      DeletionProtection: !Equals [!Ref DeletionProtection, "true"]

Outputs:
  DbInstanceArn:
    Description: ARN of the RDS instance
    Value: !GetAtt OrdersAppPostgresDb.DBInstanceArn

  DbEndpointAddress:
    Description: RDS endpoint address
    Value: !GetAtt OrdersAppPostgresDb.Endpoint.Address

  DbEndpointPort:
    Description: RDS endpoint port
    Value: !GetAtt OrdersAppPostgresDb.Endpoint.Port

  DbSubnetGroupName:
    Description: DB subnet group used for Multi-AZ placement
    Value: !Ref OrdersAppDbSubnetGroup
