AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Orders App - ALB stack (imports VPC + public subnets + ALB SG; exports target group + ALB DNS).

Parameters:
  ExportPrefix:
    Type: String
    Default: orders-app

  TargetPort:
    Type: Number
    Default: 8080

  HealthCheckPath:
    Type: String
    Default: /actuator/health/readiness

Resources:
  OrdersAppAlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: orders-app-alb
      Scheme: internet-facing
      Type: application
      IpAddressType: ipv4
      Subnets:
        - !ImportValue
          Fn::Sub: "${ExportPrefix}:PublicSubnetAzAId"
        - !ImportValue
          Fn::Sub: "${ExportPrefix}:PublicSubnetAzBId"
      SecurityGroups:
        - !ImportValue
          Fn::Sub: "${ExportPrefix}:AlbSecurityGroupId"
      Tags:
        - Key: Name
          Value: orders-app-alb

  OrdersAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: orders-app-tg
      VpcId: !ImportValue
        Fn::Sub: "${ExportPrefix}:VpcId"
      TargetType: instance
      Protocol: HTTP
      Port: !Ref TargetPort
      HealthCheckEnabled: true
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port
      HealthCheckPath: !Ref HealthCheckPath
      Matcher:
        HttpCode: "200-399"
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckIntervalSeconds: 15
      HealthCheckTimeoutSeconds: 5
      Tags:
        - Key: Name
          Value: orders-app-tg

  OrdersAppHttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref OrdersAppAlb
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref OrdersAppTargetGroup

Outputs:
  AlbDnsName:
    Value: !GetAtt OrdersAppAlb.DNSName
    Export:
      Name: !Sub "${ExportPrefix}:AlbDnsName"

  TargetGroupArn:
    Value: !Ref OrdersAppTargetGroup
    Export:
      Name: !Sub "${ExportPrefix}:AlbTargetGroupArn"
