AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Orders App - Compute stack (ASG in private app subnets; imports networking+ALB+RDS exports).

Parameters:
  ExportPrefix:
    Type: String
    Default: orders-app

  AmiId:
    Type: AWS::EC2::Image::Id
    Description: AMI ID (recommended: Amazon Linux 2023)

  InstanceType:
    Type: String
    Default: t3.micro

  DesiredCapacity:
    Type: Number
    Default: 2
    MinValue: 0

  MinSize:
    Type: Number
    Default: 2
    MinValue: 0

  MaxSize:
    Type: Number
    Default: 2
    MinValue: 0

  AppPort:
    Type: Number
    Default: 8080

  AppJarUrl:
    Type: String
    Description: Public HTTPS URL to download the Spring Boot jar

  DbName:
    Type: String
    Default: ordersdb

  DbUsername:
    Type: String

  DbPassword:
    Type: String
    NoEcho: true

Resources:
  OrdersAppEc2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "orders-app-ec2-ssm-role-${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ["sts:AssumeRole"]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: orders-app-ec2-ssm-role

  OrdersAppEc2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "orders-app-ec2-instance-profile-${AWS::StackName}"
      Roles:
        - !Ref OrdersAppEc2Role

  OrdersAppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "orders-app-launch-template-${AWS::StackName}"
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        IamInstanceProfile:
          Name: !Ref OrdersAppEc2InstanceProfile
        SecurityGroupIds:
          - !ImportValue
            Fn::Sub: "${ExportPrefix}:AppSecurityGroupId"
        UserData:
          Fn::Base64: !Sub
            - |
              #!/bin/bash
              set -euo pipefail

              dnf -y update
              dnf -y install java-21-amazon-corretto curl

              id -u ordersapp &>/dev/null || useradd --system --create-home --shell /sbin/nologin ordersapp
              mkdir -p /opt/orders-app
              chown -R ordersapp:ordersapp /opt/orders-app

              curl -fL "${AppJarUrl}" -o /opt/orders-app/app.jar
              chown ordersapp:ordersapp /opt/orders-app/app.jar
              chmod 0644 /opt/orders-app/app.jar

              cat >/etc/orders-app.env <<EOF
              SPRING_DATASOURCE_URL=${JdbcUrl}
              SPRING_DATASOURCE_USERNAME=${DbUsername}
              SPRING_DATASOURCE_PASSWORD=${DbPassword}
              APP_PORT=${AppPort}
              EOF
              chmod 0600 /etc/orders-app.env

              cat >/etc/systemd/system/orders-app.service <<'EOF'
              [Unit]
              Description=Orders App (Spring Boot)
              After=network-online.target
              Wants=network-online.target

              [Service]
              Type=simple
              User=ordersapp
              WorkingDirectory=/opt/orders-app
              EnvironmentFile=/etc/orders-app.env
              ExecStart=/usr/bin/java -jar /opt/orders-app/app.jar --server.port=$APP_PORT
              Restart=always
              RestartSec=5
              SuccessExitStatus=143

              [Install]
              WantedBy=multi-user.target
              EOF

              systemctl daemon-reload
              systemctl enable --now orders-app.service
            - JdbcUrl: !Sub
                - "jdbc:postgresql://${Addr}:${Port}/${DbName}"
                - Addr: !ImportValue
                    Fn::Sub: "${ExportPrefix}:DbEndpointAddress"
                  Port: !ImportValue
                    Fn::Sub: "${ExportPrefix}:DbEndpointPort"
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: orders-app-asg-instance

  OrdersAppAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !ImportValue
          Fn::Sub: "${ExportPrefix}:PrivateAppSubnetAzAId"
        - !ImportValue
          Fn::Sub: "${ExportPrefix}:PrivateAppSubnetAzBId"
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      DesiredCapacity: !Ref DesiredCapacity
      LaunchTemplate:
        LaunchTemplateId: !Ref OrdersAppLaunchTemplate
        Version: !GetAtt OrdersAppLaunchTemplate.LatestVersionNumber
      TargetGroupARNs:
        - !ImportValue
          Fn::Sub: "${ExportPrefix}:AlbTargetGroupArn"
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: orders-app-asg
          PropagateAtLaunch: true

Outputs:
  AutoScalingGroupName:
    Value: !Ref OrdersAppAutoScalingGroup

  AlbUrl:
    Description: Convenience output for browsing
    Value: !Sub "http://${AlbDns}/"
    Export:
      Name: !Sub "${ExportPrefix}:AlbUrl"
    Condition: AlwaysFalse

Conditions:
  # Exporting the ALB URL is optional; this condition keeps the output from exporting
  # (since exports must be unique). You can remove the Export from AlbUrl or remove this entire block.
  AlwaysFalse: !Equals ["true", "false"]
